### ISSUE TITLE
Linking static libraries

### ISSUE THREAD

**Issue by phillvancejr** [C-Chads/tinycc#1]
Hello,
I've been trying our your fork and I'm trying to link with a static library but TCC is saying that the symbols aren't found. I'm having this issue both with the tcc executable and when using libtcc.h and tcc_add_file, any ideas on how I can get this to work?

**Comment by gek169** [comment]
Not sure.
In many cases, TinyCC has issues with libraries that use SIMD instructions, such as stb-image.
TinyCC on Windows? I'm not even sure it CAN statically link.
You need a LibC on your system (TinyCC does not come with a libc)

**Comment by phillvancejr** [comment]
interesting, I'll look out for SIMD code. And by Static linking I don't mean like a completely statically linked binary on Linux, I just meant linking with an archive/.lib file. Dynamic libraries work fine but not archives, however I think I came across something that said the static library needs to be compiled by tcc. Thanks for your time, I'll keep looking. Regards

**Comment by gek169** [comment]
thanks
